# A list of trading pairs to download and backtest.
# The backtest can be run on a specific pair using its index (e.g., `make run index=0`)
# or on all of them (`make run index=all`).
trading_pairs:
  - { symbol: "BTC/USDT", timeframe: "1h", start: "2022-01-01", end: "2023-12-31" }
  - { symbol: "ETH/USDT", timeframe: "1h", start: "2022-01-01", end: "2022-12-31" }

# --- Indicator Pre-processing ---
# These indicators will be calculated for the selected trading pair.
indicators:
  - { name: "SMA", period: 50 }
  - { name: "SMA", period: 200 }

# --- Portfolio Configuration ---
portfolio:
  initial_capital: 100000
  fee_pct: 0.1

# --- Strategy Configuration ---
# This strategy will be applied to the selected trading pair(s).
strategy:
  class_name: "SMACrossoverStrategy"
  parameters:
    fast_sma_col: "SMA_50"
    slow_sma_col: "SMA_200"
    risk_pct: 0.01