# A list of trading pairs to download and backtest.
# The backtest can be run on a specific pair using its index (e.g., `make run index=0`)
# or on all of them (`make run index=all`).
trading_pairs:
  - {
      symbol: "BTC/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-07-31",
      prefix: "BTC_all",
    }
  - {
      symbol: "ETH/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "ETH_all",
    }
  - {
      symbol: "SOL/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "SOL_all",
    }
  - {
      symbol: "GALA/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "GALA_all",
    }
  - {
      symbol: "XRP/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "XRP_all",
    }
  - {
      symbol: "LTC/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "LTC_all",
    }
  - {
      symbol: "BNB/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "BNB_all",
    }
  - {
      symbol: "ADA/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "ADA_all",
    }
  - {
      symbol: "DOT/USDT",
      timeframes: ["1d"],
      start: "2021-01-01",
      end: "2025-12-31",
      prefix: "DOT_all",
  }

# --- Indicator Pre-processing ---
# These indicators will be calculated for the selected trading pair.
indicators:
  # Moving Averages
  - { name: "ma_high", period: 20 }
  - { name: "ma_low", period: 20 }

  # SuperTrend
  - { name: "supertrend", period: 10, multiplier: 2 }

  # EMAs for lower timeframe entry
  - { name: "EMA", period: 12 }
  - { name: "EMA", period: 26 }

# --- Portfolio Configuration ---
portfolio:
  initial_capital: 100000
  fee_pct: 0.05
  risk_pct: 5 # New: Risk percentage per trade

# --- Strategy Configuration ---
# This strategy will be applied to the selected trading pair(s).
strategy:
  class_name: "MovingAverageStrategy"
  timeframe: "1d" # Specify which timeframe to use for trading
  parameters:
    ma_period: 20
    supertrend_period: 10
    supertrend_multiplier: 3
# strategy:
#   class_name: "MultiTimeframeMomentumStrategy"
#   timeframe: "1h"
#   parameters:
#     higher_timeframe: "4h"
#     ema_fast_col: "EMA_12"
#     ema_slow_col: "EMA_26"
#     take_profit_pct: 0.01 # 2% take profit
