# A list of trading pairs to download and backtest.
# The backtest can be run on a specific pair using its index (e.g., `make run index=0`)
# or on all of them (`make run index=all`).
trading_pairs:
  - { 
      symbol: "BTC/USDT",
      timeframe: "1h",
      start: "2024-01-01",
      end: "2024-12-31",
    }
  - { 
      symbol: "ETH/USDT",
      timeframe: "1h",
      start: "2024-01-01",
      end: "2024-12-31",
    }

# --- Indicator Pre-processing --- 
# These indicators will be calculated for the selected trading pair.
indicators:
  # Moving Averages
  - { name: "ma_high", period: 20 }
  - { name: "ma_low", period: 20 }

  # SuperTrend
  - { name: "supertrend", period: 10, multiplier: 2 }

# --- Portfolio Configuration ---
portfolio:
  initial_capital: 100000
  fee_pct: 0.1

# --- Strategy Configuration ---
# This strategy will be applied to the selected trading pair(s).
strategy:
  class_name: "MovingAverageStrategy"
  parameters:
    ma_period: 20
    supertrend_period: 10
    supertrend_multiplier: 3
