# --- Backtest Settings ---
# Define the symbols, timeframes, and periods for the backtest runs.
backtest_settings:
  symbols:
    - "BTC/USDT"
    # - "ETH/USDT"
    # - "SOL/USDT"
    # - "GALA/USDT"
    # - "XRP/USDT"
    # - "LTC/USDT"
    # - "BNB/USDT"
    # - "ADA/USDT"
    # - "DOT/USDT"
  timeframes:
    - "4h"
  periods:
    # 2025: ["june", "july"]
    2025: []